# -*- coding: utf-8 -*-
"""Proyecto final.phy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8QYsU3Q3u1VN66c2YOm_P3zgy8xhKk4

Proyecto integrador. Sistema de gestion de pedidos para una cafeteria.

Este notebook presenta el desarrollo de un sistema que simula el proceso de atencion de pedidos de una cafeteria
"""

import datetime

"""## Estructuras de datos

En esta sección se definen las estructuras principales del sistema.

- Una tupla almacena las categorías del menú.
- Un diccionario relaciona cada producto con su precio.
- Una lista guardará temporalmente los productos seleccionados por el cliente.
"""

categorias = (
    "Bebidas",
    "Panadería",
    "Postres"
)
menu = {
    "Café Americano": 2.50,
    "Capuccino": 4.00,
    "Chocolate Caliente": 3.75,
    "Croissant": 3.25,
    "Muffin": 2.75,
    "Cheesecake": 5.00,
    "Brownie": 3.50
}
pedido = []

"""Funcion para presentar al ususrio las categorias disponibles y los productos con sus respectivos precios"""

def mostrar_menu():

    print("\n===== CAFETERÍA =====")

    print("\nCategorías disponibles:")
    for categoria in categorias:
        print("-", categoria)

    print("\nMenú:")

    for producto, precio in menu.items():
        print(f"{producto}: ${precio:.2f}")

"""prueba 1"""

mostrar_menu()

"""Despues añadimos una funcion que permita al usuario seleccionar los productos que desea comprar."""

def agregar_producto():

    while True:

        producto = input("\nIngrese el nombre del producto: ").title()

        if producto in menu:
            pedido.append(producto)
            print(f"{producto} agregado al pedido.")

        else:
            print("El producto no existe en el menú.")

        continuar = input("¿Desea agregar otro producto? (si/no): ").lower()

        if continuar != "si":
            break

"""prueba 2"""

mostrar_menu()
agregar_producto()

print(pedido)

"""En la siguiente celda se obtiene el precio de los productos seleccionados usando el diccionario menu y se calcula el valor total"""

def calcular_total():

    if len(pedido) == 0:
        print("\nNo hay productos en el pedido.")
        return

    total = 0

    for producto in pedido:
        total += menu[producto]

    print("\n===== RESUMEN DEL PEDIDO =====")

    for producto in pedido:
        print(f"- {producto}: ${menu[producto]:.2f}")

    print(f"\nTotal a pagar: ${total:.2f}")

    return total

"""prueba 3"""

mostrar_menu()

agregar_producto()

total = calcular_total()

"""Programa pincipal
En esta seccion se desarrolla el menu principal del sistema. Donde se podra ver el menu de producto, agregar articulos a la compra o cunsultar el valor.
"""

while True:

    print("\n===== SISTEMA DE PEDIDOS =====")
    print("1. Mostrar menú")
    print("2. Agregar productos")
    print("3. Ver total")
    print("4. Salir")

    opcion = input("\nSeleccione una opción: ")

    if opcion == "1":
        mostrar_menu()

    elif opcion == "2":
        agregar_producto()

    elif opcion == "3":
        calcular_total()

    elif opcion == "4":
        print("\nGracias por utilizar el sistema.")
        break

    else:
        print("Opción no válida. Intente nuevamente.")

def vaciar_pedido():

    pedido.clear()

    print("El pedido fue eliminado correctamente.")

"""Prueba final para asegurar que el sistema este funcionando correctamente"""

while True:

    print("\n===== SISTEMA DE PEDIDOS =====")
    print("1. Mostrar menú")
    print("2. Agregar productos")
    print("3. Ver total")
    print("4. Vaciar pedido")
    print("5. Salir")

    opcion = input("\nSeleccione una opción: ")

    if opcion == "1":
        mostrar_menu()

    elif opcion == "2":
        agregar_producto()

    elif opcion == "3":
        calcular_total()

    elif opcion == "4":
        vaciar_pedido()

    elif opcion == "5":
        print("\nGracias por utilizar el sistema.")
        break

    else:
        print("Opción no válida. Intente nuevamente.")